const languages = new Map<string, string>([
  ["arabic", "Arabic"],
  ["bengali", "Bengali"],
  ["chinese", "Chinese"],
  ["czech", "Czech"],
  ["danish", "Danish"],
  ["dutch", "Dutch"],
  ["english", "English"],
  ["finnish", "Finnish"],
  ["french", "French"],
  ["german", "German"],
  ["greek", "Greek"],
  ["hindi", "Hindi"],
  ["indonesian", "Indonesian"],
  ["italian", "Italian"],
  ["japanese", "Japanese"],
  ["korean", "Korean"],
  ["norwegian", "Norwegian"],
  ["polish", "Polish"],
  ["portuguese", "Portuguese"],
  ["russian", "Russian"],
  ["spanish", "Spanish"],
  ["swedish", "Swedish"],
  ["thai", "Thai"],
  ["turkish", "Turkish"],
  ["vietnamese", "Vietnamese"],
]);

export default languages;
